Repository EdiWang/Moonglade, pull requests merged in 2020-08, with the labels that each got.

#467 Deprecate jquery-validation for pre-login pages
  src/Moonglade.Web/Views/Admin/SignIn.cshtml
  src/Moonglade.Web/Views/Post/Slug.cshtml
  src/Moonglade.Web/Views/Shared/_LayoutAdmin.cshtml
  src/Moonglade.Web/bundleconfig.json
  src/Moonglade.Web/wwwroot/css/src/moonglade-base.css
Labels: UI

#468 Create admin-js-bundle
  .gitignore
  src/Moonglade.Web/Moonglade.Web.csproj
  src/Moonglade.Web/Views/Shared/_LayoutAdmin.cshtml
  src/Moonglade.Web/bundleconfig.json
Labels: UI, area-admin

#470 One key install
  README.md
  install.sh
  uninstall.sh
Labels: area-setup

#475 Update install.sh to use a magical way to detect current machine IP.
  Deployment/install.sh
Labels: area-setup
