Repository EdiWang/Moonglade, pull requests merged in 2020-03, with the labels that each got.

#348 Fix issue where changing publish date before year 1975 can make post 404
  src/Moonglade.Web/Controllers/PostController.Manage.cs
Labels: area-admin, area-post, bug

#345 Optional Dark Theme Regarding Client System Settings
  src/Moonglade.Model/Settings/AppSettings.cs
  src/Moonglade.Web/Views/Post/Slug.cshtml
  src/Moonglade.Web/appsettings.json
  src/Moonglade.Web/wwwroot/js/app/autodarklighttheme.js
Labels: UI, new feature, research

#355 Make path work on Linux so that docker won't blow up #257
  src/Moonglade.Core/SyndicationService.cs
  src/Moonglade.Core/Utils.cs
  src/Moonglade.ImageStorage.FileSystem/FileSystemImageProvider.cs
  src/Moonglade.Web.FaviconGenerator/FaviconGenerator.cs
  src/Moonglade.Web/Controllers/CategoryController.Manage.cs
  src/Moonglade.Web/Controllers/ImageController.cs
  src/Moonglade.Web/Controllers/OpmlController.cs
  src/Moonglade.Web/Controllers/SearchController.cs
  src/Moonglade.Web/Controllers/SubscriptionController.cs
  src/Moonglade.Web/Filters/DeleteSubscriptionCache.cs
  src/Moonglade.Web/Startup.cs
Labels: docker
