Repository EdiWang/Moonglade, pull requests merged in 2021-05, with the labels that each got.

#542 Migrate front-end framework to Bootstrap 5.0
  src/Moonglade.Web/Pages/Admin/AuditLogs.cshtml
  src/Moonglade.Web/Pages/Admin/BlogPage.cshtml
  src/Moonglade.Web/Pages/Admin/Category.cshtml
  src/Moonglade.Web/Pages/Admin/Comments.cshtml
  src/Moonglade.Web/Pages/Admin/EditPage.cshtml
  src/Moonglade.Web/Pages/Admin/EditPost.cshtml
  src/Moonglade.Web/Pages/Admin/FriendLink.cshtml
  src/Moonglade.Web/Pages/Admin/LocalAccount.cshtml
  src/Moonglade.Web/Pages/Admin/Menu.cshtml
  src/Moonglade.Web/Pages/Admin/Pingback.cshtml
  src/Moonglade.Web/Pages/Admin/Post.cshtml
  src/Moonglade.Web/Pages/Admin/Tags.cshtml
  src/Moonglade.Web/Pages/Admin/_PostManageHeader.cshtml
  src/Moonglade.Web/Pages/Archive.cshtml
  src/Moonglade.Web/Pages/BlogPage.cshtml
  src/Moonglade.Web/Pages/BlogPagePreview.cshtml
  src/Moonglade.Web/Pages/CategoryList.cshtml
  src/Moonglade.Web/Pages/Index.cshtml
  src/Moonglade.Web/Pages/Post.cshtml
  src/Moonglade.Web/Pages/Settings/Advanced.cshtml
  src/Moonglade.Web/Pages/Settings/Content.cshtml
  src/Moonglade.Web/Pages/Settings/CustomStyleSheet.cshtml
  src/Moonglade.Web/Pages/Settings/General.cshtml
  src/Moonglade.Web/Pages/Settings/Notification.cshtml
  src/Moonglade.Web/Pages/Settings/Subscription.cshtml
  src/Moonglade.Web/Pages/Settings/Watermark.cshtml
  src/Moonglade.Web/Pages/Shared/Components/CategoryList/Default.cshtml
  src/Moonglade.Web/Pages/Shared/Components/CommentList/Default.cshtml
  src/Moonglade.Web/Pages/Shared/Components/FriendLink/Default.cshtml
  src/Moonglade.Web/Pages/Shared/Components/Menu/Default.cshtml
  src/Moonglade.Web/Pages/Shared/_Aside.cshtml
  src/Moonglade.Web/Pages/Shared/_EnvInfo.cshtml
  src/Moonglade.Web/Pages/Shared/_Footer.cshtml
  src/Moonglade.Web/Pages/Shared/_Layout.cshtml
  src/Moonglade.Web/Pages/Shared/_LayoutAdmin.cshtml
  src/Moonglade.Web/Pages/Shared/_LightSwitch.cshtml
  src/Moonglade.Web/Pages/Shared/_PostListEntry.cshtml
  src/Moonglade.Web/Pages/SignIn.cshtml
  src/Moonglade.Web/Pages/Tags.cshtml
  src/Moonglade.Web/Pages/_ExternalLink.cshtml
  src/Moonglade.Web/Pages/_PostActions.cshtml
  src/Moonglade.Web/bundleconfig.json
  src/Moonglade.Web/wwwroot/css/3rd/bootstrap.min.css
  src/Moonglade.Web/wwwroot/css/3rd/dataTables.bootstrap5.min.css
  src/Moonglade.Web/wwwroot/css/3rd/datatables.min.css
  src/Moonglade.Web/wwwroot/css/src/admin.css
  src/Moonglade.Web/wwwroot/css/src/base.css
  src/Moonglade.Web/wwwroot/css/src/darkmode.css
  src/Moonglade.Web/wwwroot/css/src/navigation.css
  src/Moonglade.Web/wwwroot/css/src/rwd.css
  src/Moonglade.Web/wwwroot/css/src/timeline.css
  src/Moonglade.Web/wwwroot/js/3rd/bootstrap.bundle.min.js
  src/Moonglade.Web/wwwroot/js/app/admin.js
  src/Moonglade.Web/wwwroot/js/app/base.js
  src/Moonglade.Web/wwwroot/js/app/postslug.js
Labels: UI

#543 Migrate to Bootstrap Icons
  src/Moonglade.Web/Pages/Admin/AuditLogs.cshtml
  src/Moonglade.Web/Pages/Admin/BlogPage.cshtml
  src/Moonglade.Web/Pages/Admin/Category.cshtml
  src/Moonglade.Web/Pages/Admin/Comments.cshtml
  src/Moonglade.Web/Pages/Admin/FriendLink.cshtml
  src/Moonglade.Web/Pages/Admin/LocalAccount.cshtml
  src/Moonglade.Web/Pages/Admin/Menu.cshtml
  src/Moonglade.Web/Pages/Admin/Pingback.cshtml
  src/Moonglade.Web/Pages/Admin/Post.cshtml
  src/Moonglade.Web/Pages/Admin/PostDraft.cshtml
  src/Moonglade.Web/Pages/Admin/RecycleBin.cshtml
  src/Moonglade.Web/Pages/Admin/Tags.cshtml
  src/Moonglade.Web/Pages/Admin/_DiagnosisHeader.cshtml
  src/Moonglade.Web/Pages/Admin/_PostManageHeader.cshtml
  src/Moonglade.Web/Pages/Archive.cshtml
  src/Moonglade.Web/Pages/CategoryList.cshtml
  src/Moonglade.Web/Pages/Index.cshtml
  src/Moonglade.Web/Pages/Post.cshtml
  src/Moonglade.Web/Pages/Settings/_SettingsHeader.cshtml
  src/Moonglade.Web/Pages/Shared/Components/CategoryList/Default.cshtml
  src/Moonglade.Web/Pages/Shared/Components/RssList/Default.cshtml
  src/Moonglade.Web/Pages/Shared/_Aside.cshtml
  src/Moonglade.Web/Pages/Shared/_Footer.cshtml
  src/Moonglade.Web/Pages/Shared/_Layout.cshtml
  src/Moonglade.Web/Pages/Shared/_LayoutAdmin.cshtml
  src/Moonglade.Web/Pages/Shared/_PostListEntry.cshtml
  src/Moonglade.Web/Pages/_PostActions.cshtml
  src/Moonglade.Web/bundleconfig.json
  src/Moonglade.Web/wwwroot/css/3rd/bootstrap-icons.css
  src/Moonglade.Web/wwwroot/css/src/admin.css
  src/Moonglade.Web/wwwroot/css/src/base.css
  src/Moonglade.Web/wwwroot/css/src/fonts.css
  src/Moonglade.Web/wwwroot/webfonts/bootstrap-icons.woff
  src/Moonglade.Web/wwwroot/webfonts/bootstrap-icons.woff2
  src/Moonglade.Web/wwwroot/webfonts/icomoonglade.svg
  src/Moonglade.Web/wwwroot/webfonts/icomoonglade.ttf
  src/Moonglade.Web/wwwroot/webfonts/icomoonglade.woff
Labels: UI

#545 Check for new release
  src/Moonglade.Core/Moonglade.Core.csproj
  src/Moonglade.Core/ReleaseCheckerClient.cs
  src/Moonglade.Web/Controllers/SettingsController.cs
  src/Moonglade.Web/Models/Settings/CheckNewReleaseResult.cs
  src/Moonglade.Web/Pages/Settings/Advanced.cshtml
  src/Moonglade.Web/Startup.cs
  src/Moonglade.Web/appsettings.json
  src/Tests/Moonglade.Core.Tests/ReleaseCheckerClientTests.cs
  src/Tests/Moonglade.Web.Tests/Controllers/SettingsControllerTests.cs
Labels: area-settings

#551 Fix an issue that the color of the badge 'Saved successfully' is red …
  src/Moonglade.Web/wwwroot/js/app/base.js
Labels: area-admin
